apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rag-app
  template:
    metadata:
      labels:
        app: rag-app
    spec:
      containers:
      - name: rag-app
        image: srinu445/rag-app:v1
        ports:
        - containerPort: 8501
        env:
        - name: GOOGLE_API_KEY
          valueFrom:
            secretKeyRef:
              name: gemini-secret
              key: GOOGLE_API_KEY
